# Generated by Django 3.1.4 on 2021-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('job_id', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('commission_pct', models.FloatField()),
                ('manager_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
            ],
        ),
    ]
