# Generated by Django 3.1.4 on 2021-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
    ]
