# Generated by Django 3.1.4 on 2021-01-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210103_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jobs', models.ManyToManyField(to='workers.Workers')),
            ],
        ),
        migrations.AddField(
            model_name='workers',
            name='paradigm',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='workers.paradigm'),
            preserve_default=False,
        ),
    ]
