# Generated by Django 3.1.4 on 2021-01-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20210104_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobs',
            field=models.ManyToManyField(to='workers.Paradigm'),
        ),
    ]
