# Generated by Django 3.1.4 on 2021-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20210104_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='paradigm',
        ),
        migrations.AlterField(
            model_name='workers',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.paradigm'),
        ),
    ]
