# Generated by Django 3.1.4 on 2021-01-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20210104_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobs',
        ),
        migrations.AddField(
            model_name='paradigm',
            name='jobs',
            field=models.ManyToManyField(to='workers.Workers'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.job'),
        ),
    ]
