# Generated by Django 3.1.4 on 2021-01-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20210104_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs_rel', to='workers.Workers'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='job_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Paradigm',
        ),
    ]
