# Generated by Django 3.1.4 on 2021-01-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20210104_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='job_id',
            new_name='job',
        ),
    ]
