# Generated by Django 3.1.4 on 2021-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20210104_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='job',
        ),
        migrations.AlterField(
            model_name='job',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='workers.Workers'),
        ),
    ]
