# Generated by Django 3.1.4 on 2021-01-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_auto_20210104_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='manager_id',
        ),
    ]
