# Generated by Django 3.1.4 on 2021-01-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_auto_20210104_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='manager_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
