# Generated by Django 3.1.4 on 2021-01-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_auto_20210104_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='commission_pct',
        ),
    ]
