# Generated by Django 3.1.4 on 2021-01-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_remove_workers_commission_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='commission_pct',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
